version: '3.1'
services:

  backend:
    build: ./backend
    container_name: cloud-project-backend
    restart: always
    ports:
      - 4000:4000

  frontend:
    build: ./frontend
    container_name: cloud-project-frontend
    restart: always
    ports:
      - 3000:3000
